name: smart_flutter_validator
description: A powerful and composable form validation package for Flutter.
version: 1.0.0
repository: https://github.com/Thanuzeera/smart_flutter_validator
documentation: https://github.com/Thanuzeera/smart_flutter_validator#readme
issue_tracker: https://github.com/Thanuzeera/smart_flutter_validator/issues
homepage: https://github.com/Thanuzeera/smart_flutter_validator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
